### ISSUE TITLE
occur indexError

### ISSUE THREAD

**Issue by CodeMadUser** [USTC-JialunPeng/Diverse-Structure-Inpainting#24]
hello,when I use your code training, it occurs indexError: 
in this part:
    for i in range(4):
        gt_i = ((gt[i] + 1.) * 127.5).astype(np.uint8)
        masked_i = ((masked[i] + 1.) * 127.5).astype(np.uint8)
        complete_i = ((complete[i] + 1.) * 127.5).astype(np.uint8)
        recons_gt_i = ((recons_gt[i] + 1.) * 127.5).astype(np.uint8)

> train_structure_generator.py：
Traceback (most recent call last):
  File "train_structure_generator.py", line 366, in <module>
    nn.structure_visual(gt_np, masked_np, recons_gen_np, recons_gt_np, (i + 1), args.image_size, folder_path)
  File "D:\pythonProject\5_19\VQ_VAE\net\nn.py", line 173, in structure_visual
    gt_i = ((gt[i] + 1.) * 127.5).astype(np.uint8)
IndexError: index 1 is out of bounds for axis 0 with size 1

How many dimensions is the parameter gt? What data parameter is gt?thank you

**Comment by USTC-JialunPeng** [comment]
It is a naive visualization code that requires a batch size of at least 4 per GPU. 

Please refer to #21 to visualize only 1 image if your batch size per GPU is less than 4.

**Comment by CodeMadUser** [comment]
ok,I get it .thank you for your help.
