### ISSUE TITLE
Tensorflow version problem

### ISSUE THREAD

**Issue by chandni-dev** [USTC-JialunPeng/Diverse-Structure-Inpainting#30]
23-07-14 11:47:14.743679: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-07-14 11:47:15.646115: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
Traceback (most recent call last):
  File "/content/drive/MyDrive/Diverse-Structure-Inpainting/train_vqvae.py", line 9, in <module>
    from net.vqvae import vq_encoder_spec, vq_decoder_spec
  File "/content/drive/MyDrive/Diverse-Structure-Inpainting/net/vqvae.py", line 3, in <module>
    from tensorflow.contrib.framework.python.ops import arg_scope
ModuleNotFoundError: No module named 'tensorflow.contrib'

How to resolve version problem

**Comment by chandni-dev** [comment]
urgent pls.......

**Comment by USTC-JialunPeng** [comment]
Please note that tf.contrib no longer exist in Tensorflow 2.x. This code was tested with TensorFlow 1.12.0 (later versions may work, excluding 2.x).
